#!/usr/bin/env bash
#
# This script is sourced when bash is started as an interactive login shell


[[ -n "$DEBUG" ]] && echo bash_profile

# Source optional local configuration
[[ -f "${BASH_SOURCE[0]}.local" ]] && . "${BASH_SOURCE[0]}.local"

# Only source bashrc for interactive prompts
[[ $- != *i* ]] || . "$HOME/.bashrc"
