#!/usr/bin/env bash
# 
# This script is sourced when bash is started as an interactive login shell

#[[ ! $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

# Source optional local configuration
[[ -f "${BASH_SOURCE[0]}.local" ]] && . "${BASH_SOURCE[0]}.local"

# Only source bashrc for interactive prompts
[[ $- != *i* ]] || . "$HOME/.bashrc"
