#!/usr/bin/env sh

test -n "$DEBUG" && echo profile

BASH_DIR="$HOME/.bash"
ZSH_DIR="$HOME/.zsh"

# Use BASH_SCRIPTS to load zsh modules from $BASH_DIR/scripts on-demand and in the order specified.
# BASH_SCRIPTS=()

# Use ZSH_SCRIPTS to load zsh modules from $ZSH_DIR/scripts on-demand and in the order specified.
# ZSH_SCRIPTS=()

# SSH_IDENTITIES is used by the ssh-agent.bash script to automatically load identities from $HOME/.ssh/.
SSH_IDENTITIES=(id_rsa)

# {{{ Source files
# Source common bash configuration.
test -r "${BASH_DIR}/init.sh" && . "${BASH_DIR}/init.sh"

# Source common zsh configuration.
if test -n "$ZSH_VERSION";then
    test -r "${ZSH_DIR}/init.sh" && . "${ZSH_DIR}/init.sh"
fi

# Source optional local configuration
test -r "$HOME/.profile.local" && . "$HOME/.profile.local"
# }}}


