#!/usr/bin/env sh

test "$DEBUG" && echo profile

BASH_DIR="$HOME/.bash"
ZSH_DIR="$HOME/.zsh"

# SSH_IDENTITIES is used by the ssh-agent.sh script to automatically load identities from $HOME/.ssh/.
SSH_IDENTITIES=(id_rsa)

# Use BASH_SCRIPTS to load zsh modules from $BASH_DIR/scripts on-demand and in the order specified.
# BASH_SCRIPTS=()

# Use ZSH_SCRIPTS to load zsh modules from $ZSH_DIR/scripts on-demand and in the order specified.
# ZSH_SCRIPTS=()


#  Source files
# Source common bash configuration.
test -r "$BASH_DIR/init.sh" && . "$BASH_DIR/init.sh"

# Source common zsh configuration.
if test "$ZSH_VERSION";then
    test -r "$ZSH_DIR/init.sh" && . "$ZSH_DIR/init.sh"
fi

# Source optional local configuration
test -r "$HOME/.profile.local" && . "$HOME/.profile.local"


