(xbindkey '("XF86AudioMute") "pamixer --toggle-mute")
(xbindkey '("XF86AudioRaiseVolume") "pamixer --increase 5")
(xbindkey '("XF86AudioLowerVolume") "pamixer --decrease 5")
(xbindkey '("XF86AudioMicMute") "amixer -q set Capture toggle")
(xbindkey '("XF86MonBrightnessDown") "xbacklight -dec 7")
(xbindkey '("XF86MonBrightnessUp") "xbacklight -inc 7")
(xbindkey '("XF86Display") "")
(xbindkey '("XF86WLAN") "")
(xbindkey '("XF86Tools") "")
(xbindkey '("XF86Search") "")
(xbindkey '("XF86LaunchA") "")
(xbindkey '("XF86Explorer") "spacefm")
(xbindkey '("XF86Calculator") "gnome-calculator")
(xbindkey '("XF86HomePage") "firefox")
