#
# Executes commands at login pre-zshrc.
#
[[ -d ~/.profile ]] && source ~/.profile

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

TMPPREFIX="${TMPDIR%/}/zsh"
