#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source local configuration
LOCALFILE="$HOME/.zshrc.local"
if [[ -f "$LOCALFILE" ]]; then
    source "$LOCALFILE"
fi

