#!/bin/bash

COMMAND="xbacklight"
STEP=7

case "$1" in
    min)    xbacklight -set 0;;
    max)    xbacklight -set 100;;
    +)      xbacklight -inc ${STEP};;
    -)      xbacklight -dec ${STEP};;
    [0-9]*) xbacklight -set $1;;
    *)  echo "Usage: hell {0-100,+,-,min,max}" && exit 1;;
esac

CUR_VAL=$(xbacklight -get)
printf "%.0f\n" ${CUR_VAL}
