#!/bin/bash
#

usage() {
    local script_name=$(basename $0)
    cat << EOF
Description:
    Wrapper for playerctl to control media playback

Usage:
    $script_name (play-pause | pause | prev | next | status | mute)

EOF
    exit
}
[[ "$#" -lt 1 ]] && usage

SPOTIFY_FOUND=$(pgrep spotify)
COMMAND="playerctl $1"
[[ $1 == mute ]] && COMMAND="pamixer --toggle-mute"
if [[ $HOSTNAME != "htpc" ]] && [[ -z $SPOTIFY_FOUND ]]; then
    ssh slave@htpc ${COMMAND}
else
    eval $(${COMMAND})
fi
