#!/usr/bin/perl -w
use strict;
use warnings;

my $searchPath = '~/.local/wallpapers/';   # Set to the directory you want to have searched for photos
my $switchTime = 60;               # Edit to the number of seconds between photo switches

if (@ARGV) { $switchTime = $ARGV[0] }

my @photos = `find $searchPath -type f | grep [jJ][pP][eE]*[gG]`;             
chomp(@photos);
my $photo;

while(1)
{
    $photo = $photos[rand($#photos)];
    `feh --bg-scale "$photo"`;
    sleep($switchTime);
}
