#!/bin/sh
# ~/.xinitrc
#

if [ -f "$HOME/.xprofile" ]; then
    . "$HOME/.xprofile"
fi

## Startup {{{
have() { command -v "$@" &>/dev/null; }
apps="nm-applet chromium urxvt"
for app in $apps; do
    have $app && $app &
done
#have nm-applet && nm-applet &
#have chromium && chromium &
#have urxvt && urxvt &
have pcmanfm && pcmanfm -d &
# }}}

exec systemd-cat awesome
