#!/bin/sh
# ~/.xprofile
#

## Basic config {{{
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps.
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Load global xinit configs.
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Ensure that GTK themes are applied uniformly in the Desktop Environment
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Where the default Home folders have not already been created, generate them
if [ -x /usr/bin/xdg-user-dirs-update ]; then
    /usr/bin/xdg-user-dirs-update
fi
## }}}

#autorandr -c &
#xautolock -time 30 -locker "systemctl suspend" -detectsleep &
#xset s off dpms 0 0 300
#start-pulseaudio-x11
setxkbmap gb
xmodmap ~/.Xmodmap

xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" 0.3
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Horizontal Scroll Enabled" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Middle Emulation Enabled" 1

