#!/bin/sh
# ~/.xprofile
#

autorandr -c &
xautolock -time 30 -locker "systemctl suspend" -detectsleep &
xset s off dpms 0 0 300
start-pulseaudio-x11
setxkbmap uk
xmodmap ~/.Xmodmap

xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5
xinput set-prop "TPPS/2 IBM TrackPoint" "Device Accel Constant Deceleration" 0.3

