#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME, XARGS.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g -K
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
: ${XARGS:=/usr/bin/xargs}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/max/.dotfiles/tag-awesome/config/awesome" "/home/max/.config/awesome"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/brightness" "/home/max/.bin/brightness"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/memory" "/home/max/.bin/memory"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/package-summary" "/home/max/.bin/package-summary"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/playerctl-wrapper" "/home/max/.bin/playerctl-wrapper"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/q" "/home/max/.bin/q"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/random-wallpaper" "/home/max/.bin/random-wallpaper"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/sanitize-filename" "/home/max/.bin/sanitize-filename"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/scrot-wrapper" "/home/max/.bin/scrot-wrapper"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/show-colors" "/home/max/.bin/show-colors"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/show-pipes" "/home/max/.bin/show-pipes"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/snp" "/home/max/.bin/snp"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/spotify-controller" "/home/max/.bin/spotify-controller"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/sprunge" "/home/max/.bin/sprunge"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/ssdbench" "/home/max/.bin/ssdbench"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/thinkpad-theft" "/home/max/.bin/thinkpad-theft"
handle_file_ln "/home/max/.dotfiles/tag-bin/bin/updatehosts" "/home/max/.bin/updatehosts"
handle_file_ln "/home/max/.dotfiles/tag-cvim/cvimrc" "/home/max/.cvimrc"
handle_file_ln "/home/max/.dotfiles/tag-git/gitconfig" "/home/max/.gitconfig"
handle_file_ln "/home/max/.dotfiles/tag-git/gitignore.global" "/home/max/.gitignore.global"
handle_file_ln "/home/max/.dotfiles/tag-gpg/gnupg/gpg-agent.conf" "/home/max/.gnupg/gpg-agent.conf"
handle_file_ln "/home/max/.dotfiles/tag-gpg/gnupg/gpg.conf" "/home/max/.gnupg/gpg.conf"
handle_file_ln "/home/max/.dotfiles/tag-pentadactyl/pentadactylrc" "/home/max/.pentadactylrc"
handle_file_ln "/home/max/.dotfiles/tag-ssh/ssh/config" "/home/max/.ssh/config"
handle_file_ln "/home/max/.dotfiles/tag-theme-solarized-dark/Xresources" "/home/max/.Xresources"
handle_file_ln "/home/max/.dotfiles/tag-theme-solarized-dark/dircolors" "/home/max/.dircolors"
handle_file_ln "/home/max/.dotfiles/tag-tmux/tmux.conf" "/home/max/.tmux.conf"
handle_file_ln "/home/max/.dotfiles/tag-vim/vimrc" "/home/max/.vimrc"
handle_file_ln "/home/max/.dotfiles/tag-vimperator/vimperatorrc" "/home/max/.vimperatorrc"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zprofile" "/home/max/.zprofile"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/LICENSE.md" "/home/max/.zsh/zsh-git-prompt/LICENSE.md"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/Setup.hs" "/home/max/.zsh/zsh-git-prompt/Setup.hs"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/git-prompt.cabal" "/home/max/.zsh/zsh-git-prompt/git-prompt.cabal"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/gitstatus.py" "/home/max/.zsh/zsh-git-prompt/gitstatus.py"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/screenshot.png" "/home/max/.zsh/zsh-git-prompt/screenshot.png"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/src/BranchParse.hs" "/home/max/.zsh/zsh-git-prompt/src/BranchParse.hs"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/src/Main.hs" "/home/max/.zsh/zsh-git-prompt/src/Main.hs"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/src/StatusParse.hs" "/home/max/.zsh/zsh-git-prompt/src/StatusParse.hs"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/src/TestBranchParse.hs" "/home/max/.zsh/zsh-git-prompt/src/TestBranchParse.hs"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/src/TestFunctional.hs" "/home/max/.zsh/zsh-git-prompt/src/TestFunctional.hs"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/src/Utils.hs" "/home/max/.zsh/zsh-git-prompt/src/Utils.hs"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zsh/zsh-git-prompt/zshrc.sh" "/home/max/.zsh/zsh-git-prompt/zshrc.sh"
handle_file_ln "/home/max/.dotfiles/tag-zsh/zshrc" "/home/max/.zshrc"
