#!/bin/sh
# ~/.xprofile
#

# X11 environment
xrdb -merge ~/.Xresources
start-pulseaudio-x11
setxkbmap uk
xmodmap ~/.Xmodmap
#xbindkeys
xset s off dpms 0 0 300

# evdev
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5
xinput set-prop "TPPS/2 IBM TrackPoint" "Device Accel Constant Deceleration" 0.4

