#!/usr/bin/env sh

fix_permissions() {
  local arg

  for arg; do
    if [ -d "$arg" ]; then
      chmod 700 "$arg"
    elif [ -f "$arg" ]; then
      chmod 600 "$arg"
    fi
  done
}

configure_vim() {
  local vim_dir="$HOME/.vim"
  local plug_file="$vim_dir/autoload/plug.vim"

  mkdir -p "$vim_dir/swaps" "$vim_dir/backups"
  if [ ! -f "$plug_file" ]; then
    curl -fLo "$plug_file" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  vim +PlugInstall! +qa
}

fix_permissions ~/.config/gnupg ~/.ssh
configure_vim

