#!/usr/bin/env bash

logger() { echo "$@"; }

apply_cygwin_settings() {
    # Use native NTFS symlinks instead of "fake" cygwin symlinks.
    export CYGWIN="winsymlinks:native"
}

apply_system_specific_setup() {
    local system="$(uname -o)"

    case "$system" in
        Cygwin)
            apply_cygwin_settings
        ;;
        GNU/Linux)
        ;;
        Darwin)
        ;;
        *)
            logger "Did not recognize Operating System $system"
        ;;
    esac
}

main() {
    apply_system_specific_setup
}

main
