#!/usr/bin/env bash
#

# Use a simple prompt
PS1='[\u@\h \W]\$ '

# Initialize bash config
BASH_PLUGINS=(env utilities z git archlinux)
[[ -f "$HOME/.bash/init.sh" ]] && source "$HOME/.bash/init.sh"

# Source optional local configuration file
[[ -f "${BASH_SOURCE[0]}.local" ]] && source "${BASH_SOURCE[0]}.local"
