#!/usr/bin/env bash
# 
# This script is sourced when bash is started as an interactive login shell

# Source optional local configuration
[[ -f "${BASH_SOURCE[0]}.local" ]] && source "${BASH_SOURCE[0]}.local"

# Only source bashrc for interactive prompts
[[ $- != *i* ]] || . "$HOME/.bashrc"

