#!/usr/bin/env bash
#

# Use a simple prompt
PS1='[\u@\h \W]\$ '

# Initialize bash config
POST_PLUGINS=(archlinux common-aliases git git-extras git-flow sudo systemd tmux ssh-agent z)
[[ -f "$HOME/.bash/init.sh" ]] && source "$HOME/.bash/init.sh"

# Source optional local configuration file
[[ -f "${BASH_SOURCE[0]}.local" ]] && source "${BASH_SOURCE[0]}.local"
