#!/usr/bin/env bash
# 
# This script is run when bash starts

# Source our basic environment
[[ -f "$HOME/.profile" ]] && source "$HOME/.profile"

LOCALFILE="$HOME/.bash_profile.local"
[[ -f "$LOCALFILE" ]] && source "$LOCALFILE"

# Only source bashrc for interactive prompts
[[ $- != *i* ]] || . "$HOME/.bashrc"

