#!/usr/bin/env zsh
#
# `.zlogin' is sourced in login shells. It should contain commands that should be executed only in login shells.
# It is not the place for alias definitions, options, environment variable settings, etc.; as a general rule, it
# should not change the shell environment at all. Rather, it should be used to set the terminal type and run a series
# of external commands (fortune, msgs, etc).

[[ "$DEBUG" ]] && echo zlogin

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Source optional local configuration file.
[[ -f "$HOME/.zlogin.local" ]] && . "$HOME/.zlogin.local"
