#!/usr/bin/env zsh
#
# `.zlogout' is sourced when a login shells exit.

[[ "$DEBUG" ]] && echo zshenv

# Source optional local configuration file.
[[ -f "$HOME/.zlogout.local" ]] && . "$HOME/.zlogout.local"
