#!/usr/bin/env zsh
#
# `.zprofile' is similar to `.zlogin' (i.e. should only be sourced for login shells), except that it is sourced
# before `.zshrc'. It is meant as an alternative to `.zlogin' for ksh fans; the two are not intended to be
# used together, although this could certainly be done if desired.
# Note that on ArchLinux ~/.zprofile sources /etc/zsh/zprofile which in turn sources /etc/profile and overrides $PATH.
# Consequently, PATH (or any /etc/profile overrides) should be made in ~/.zshrc.

[[ "$DEBUG" ]] && echo zprofile

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

TMPPREFIX="${TMPDIR%/}/zsh"

# Source optional local configuration file.
[[ -f "${HOME}/.zprofile.local" ]] && . "${HOME}/.zprofile.local"

