#!/usr/bin/env zsh
#
# `.zshenv' is sourced on all invocations of the shell, unless the -f option is set. It should contain commands to set
# the command search path, plus other important environment variables. It should not contain commands that produce
# output or assume the shell is attached to a tty.

[[ "$DEBUG" ]] && echo zshenv

# Make sure TMPDIR is defined. Otherwise, temp file creation during shell initialization might fail, e.g. with
# 'can't create temp file for here document: permission denied'.
TMPDIR="${TMPDIR:-/tmp}"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  . "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Source optional local configuration file.
[[ -f "$HOME/.zshenv.local" ]] && . "$HOME/.zshenv.local"
