#!/usr/bin/env zsh

alias -g ...="../.."
alias -g ....="../../.."
alias -g .....="../../../.."
alias -g CA="2>&1 | cat -A"
alias -g G="| grep"
alias -g GI="| grep -i"
alias -g GV="| grep -iv"
alias -g H="| head"
alias -g L="| less"
alias -g LL="2>&1 | less"
alias -g N="&>/dev/null"
alias -g N1="1>/dev/null"
alias -g N2="2>/dev/null"
alias -g S="| sort"
alias -g SP="| curl -F 'sprunge=<-' http://sprunge.us"
alias -g T="| tail"
alias -g VAR=">>$HOME/.logs/var.txt"
alias -g WC="| wc -l"
alias -g X="| xargs"
