#!/usr/bin/env zsh
#

[[ -n "$DEBUG" ]] && echo zshrc

# {{{ Source configurations
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  . "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Initialize shared settings
[[ -f "${HOME}/.profile" ]] && . "${HOME}/.profile"
# }}}

# {{{ Customizations here

# }}}

# Source optional local configuration file.
[[ -f "${HOME}/.zshrc.local" ]] && . "${HOME}/.zshrc.local"

export PATH="$HOME/.bin:$PATH"
source /Users/max/.asdf/asdf.sh
