#!/usr/bin/env zsh
#

# {{{ Source configurations
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  . "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Initialize shared settings
[[ -f "${HOME}/.profile" ]] && . "${HOME}/.profile"
# }}}

# {{{ Customizations here
if command -v fzf >/dev/null 2>&1; then
  source <(fzf --zsh)
fi
# }}}

# Source optional local configuration file.
[[ -f "${HOME}/.zshrc.local" ]] && . "${HOME}/.zshrc.local"

