#!/usr/bin/env zsh
#

# {{{ Source configurations
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  . "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Initialize shared settings
[[ -f "$HOME/.profile" ]] && . "$HOME/.profile"

# Source optional local configuration file.
[[ -f "${0}.local" ]] && . "${0}.local"